### ISSUE TITLE
No such file or directory: 'data/word2vec_from_glove_300.vec'

### ISSUE THREAD

**Issue by greatgeekgrace** [YerevaNN/R-NET-in-Keras#8]
There goes wrong when I run 
` preprocessing.py data/train_parsed.json --outfile data/train_data_str.pkl --include_str`

```
IOError: [Errno 2] No such file or directory: 'data/word2vec_from_glove_300.vec'
WARNING:CoreNLP_PyWrapper:Killing subprocess 79059
INFO:CoreNLP_PyWrapper:Subprocess seems to be stopped, exit code -9
```
Then what is the word2vec_from_glove_300.vec, and how can I get it?

**Comment by mahnerak** [comment]
It's the same `glove.840B.300d.txt` file, but in word2vec 
format. (Can be downloaded here: http://nlp.stanford.edu/data/glove.840B.300d.zip)
After downloading you need to unzip the file (say, in `data/` directory), then run 
```bash
python -m gensim.scripts.glove2word2vec –input data/glove.840B.300d.txt –output data/word2vec_from_glove_300.vec
```
in order to convert it to word2vec format.

Thanks for noticing that. I'll update instructions in README page ASAP.

**Comment by greatgeekgrace** [comment]
That goes very well. Thanks!
And you have a typo on the arguments of `input` and `output`, which should have double hyphens. But that is not a big problem.

**Comment by mahnerak** [comment]
Now word2vec model is being downloaded automatically.
Closing the issue.
